#!/bin/bash
# Script to transfer repository to new private location with full history

echo "=== Repository Transfer Script ==="
echo "This script will help you transfer your AI Marketing Agent to a private repository"
echo "while preserving all commit history."
echo ""

echo "Step 1: After creating your new PRIVATE repository on GitHub, run these commands:"
echo ""
echo "# Add the new private repository as a remote (replace YOUR_NEW_REPO_URL)"
echo "git remote add private https://github.com/rafael1505/YOUR_NEW_PRIVATE_REPO_NAME.git"
echo ""
echo "# Push all branches and tags to the new private repository"
echo "git push private --all"
echo "git push private --tags"
echo ""
echo "# Verify the transfer worked"
echo "git remote -v"
echo ""
echo "Step 2: Update origin to point to private repository:"
echo "git remote remove origin"
echo "git remote rename private origin"
echo ""
echo "Step 3: Verify everything is working:"
echo "git remote -v"
echo "git log --oneline | head -5"
echo ""
echo "Step 4: Delete the old public repository:"
echo "1. Go to https://github.com/rafael1505/ai-marketing-agent"
echo "2. Click Settings (at the bottom of the sidebar)"
echo "3. Scroll to 'Danger Zone'"
echo "4. Click 'Delete this repository'"
echo "5. Type the repository name to confirm deletion"
echo ""
echo "=== Current Repository Status ==="
echo "Current remotes:"
git remote -v
echo ""
echo "Recent commits (will be preserved):"
git log --oneline | head -5
echo ""
echo "Total files to transfer:"
git ls-files | wc -l
