#!/bin/bash
# GitHub Setup Script for AI Marketing Agent

echo "=== GitHub Repository Setup ==="
echo "Please follow these steps:"
echo ""
echo "1. Update your Git configuration with your real credentials:"
echo "   git config --global user.name \"Your Real Name\""
echo "   git config --global user.email \"your.github.email@example.com\""
echo ""
echo "2. Create a new repository on GitHub:"
echo "   - Go to https://github.com"
echo "   - Click '+' > 'New repository'"
echo "   - Name: ai-marketing-agent"
echo "   - DO NOT initialize with README/gitignore"
echo "   - Click 'Create repository'"
echo ""
echo "3. Connect to your GitHub repository:"
echo "   Replace YOUR_USERNAME with your GitHub username:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/ai-marketing-agent.git"
echo ""
echo "4. Push your code to GitHub:"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "5. Verify the connection:"
echo "   git remote -v"
echo ""
echo "=== Current Repository Status ==="
git log --oneline -5
echo ""
echo "Total files committed: $(git ls-files | wc -l)"
echo ""
echo "Your repository is ready to be pushed to GitHub!"
