#!/bin/bash
#!/usr/bin/env bash
# Frontend Startup Script
# Ensures proper configuration for connecting to the API server

# Configuration variables
API_PORT=8088
API_HOST="127.0.0.1"
API_URL="http://${API_HOST}:${API_PORT}"
NEXT_PORT=3000

# Colors for terminal output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== AI Marketing Agent Frontend Startup ===${NC}"
echo "This script will configure and start the Next.js frontend"

# Check if API server is running
echo -e "\n${YELLOW}Checking API server status...${NC}"
if curl -s --head --fail "${API_URL}/api/v1/diagnostic/health" > /dev/null; then
    echo -e "${GREEN}✓ API server is running at ${API_URL}${NC}"
else
    echo -e "${RED}✗ API server is not running or not accessible${NC}"
    echo -e "${YELLOW}Starting the API server first...${NC}"
    
    # Start the API server in a separate terminal/process
    # Using nohup to keep it running after this script completes
    echo "Running API server startup script..."
    python startup_server.py &
    
    # Give it time to start
    sleep 5
    
    # Check again
    if curl -s --head --fail "${API_URL}/api/v1/diagnostic/health" > /dev/null; then
        echo -e "${GREEN}✓ API server started successfully${NC}"
    else
        echo -e "${RED}✗ Failed to start API server${NC}"
        echo "Please run 'python startup_server.py' in a separate terminal and try again"
        echo "You can continue, but the frontend may not be able to connect to the API"
    fi
fi

# Install or update frontend dependencies
echo -e "\n${YELLOW}Checking frontend dependencies...${NC}"
cd frontend

if [ ! -d "node_modules" ] || [ ! -f "node_modules/.package-lock.json" ]; then
    echo "Installing frontend dependencies..."
    npm install
else
    echo -e "${GREEN}✓ Frontend dependencies are already installed${NC}"
    echo "To update dependencies, run 'npm install' in the frontend directory"
fi

# Create environment variables file for Next.js
echo -e "\n${YELLOW}Setting up environment variables...${NC}"
cat > .env.development.local << EOL
# Generated by startup script
NEXT_PUBLIC_API_URL=${API_URL}
NEXT_PUBLIC_DEVELOPMENT=true
NEXT_PUBLIC_AUTH_TOKEN=DEVELOPMENT_MOCK_TOKEN_FOR_TESTING
EOL
echo -e "${GREEN}✓ Environment variables configured${NC}"

# Start Next.js development server
echo -e "\n${YELLOW}Starting Next.js development server...${NC}"
echo "The frontend will be available at http://localhost:${NEXT_PORT}"
echo -e "${GREEN}Press Ctrl+C to stop the server${NC}\n"

# Start Next.js
npm run dev

# Exit with success
exit 0
